---
abstract: 'GitHub WebHook receiver as Plack application'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-GitHub-WebHook
requires:
  JSON: 2.0
  Plack: 1.0
  Plack::Middleware::Access: 0.3
  perl: 5.010
resources:
  bugtracker: https://github.com/nichtich/Plack-App-GitHub-WebHook/issues
  homepage: https://github.com/nichtich/Plack-App-GitHub-WebHook
  repository: https://github.com/nichtich/Plack-App-GitHub-WebHook.git
version: 0.3
